"""
Materialize the Lumora demo project artifacts.

This script exists so the training repository contains concrete synthetic CSVs,
tables, and deck inputs. Figures are intentionally generated by Stata in
code/stata/04_make_figures.do.
"""

from __future__ import annotations

import csv
import json
import math
import random
from collections import Counter, defaultdict
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw"
INTERMEDIATE = ROOT / "data" / "intermediate"
PROCESSED = ROOT / "data" / "processed"
TABLES = ROOT / "outputs" / "tables"
FIGURES = ROOT / "outputs" / "figures"
QA = ROOT / "outputs" / "qa_reports"

SEED = 20260630


def ensure_dirs() -> None:
    for path in [RAW, INTERMEDIATE, PROCESSED, TABLES, FIGURES, QA]:
        path.mkdir(parents=True, exist_ok=True)


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        raise ValueError(f"No rows for {path}")
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def parse_date(value: str) -> date:
    return date.fromisoformat(value)


def mean(values: list[float]) -> float:
    values = [v for v in values if v is not None and not math.isnan(v)]
    return sum(values) / len(values) if values else float("nan")


def pct(num: float, den: float) -> float:
    return 100 * num / den if den else 0.0


def fmt(x: float, digits: int = 1) -> str:
    if math.isnan(x):
        return ""
    return f"{x:.{digits}f}"


def generate_raw_data() -> None:
    rng = random.Random(SEED)
    regions = {
        "North": ["Aru", "Bela", "Coro"],
        "Central": ["Dima", "Elo", "Faro"],
        "South": ["Galo", "Hima", "Ila"],
        "Coast": ["Jubo", "Kalo", "Luma"],
    }
    providers = ["LumoraPay", "MobileCash", "PostBank"]
    enumerators = [f"EN{n:02d}" for n in range(1, 17)]
    field_officers = [f"FO{n:02d}" for n in range(1, 9)]

    households = []
    for i in range(1, 1201):
        region = rng.choice(list(regions))
        district = rng.choice(regions[region])
        village = f"{district}-{rng.randint(1, 18):02d}"
        hh_size = max(1, int(rng.gauss(5.2, 2.0)))
        if i in [77, 305, 911]:
            hh_size = rng.choice([0, 22, 28])
        female_head = int(rng.random() < 0.38)
        disability = int(rng.random() < 0.17)
        children_under5 = max(0, min(hh_size, int(rng.gauss(1.1, 1.0))))
        school_age = max(0, min(hh_size, int(rng.gauss(1.7, 1.3))))
        pmt = round(max(5, min(95, rng.gauss(45, 18) - 8 * disability - 4 * female_head)), 1)
        eligible = int(pmt <= 48 or disability == 1)
        enum = rng.choice(enumerators)
        if district == "Ila":
            enum = rng.choice(["EN03", "EN04", "EN11"])
        missing_pmt = enum == "EN11" and rng.random() < 0.16
        survey_date = date(2025, 3, 1) + timedelta(days=rng.randint(0, 42))
        food_bl = max(0, min(12, round(rng.gauss(6.5 + 0.04 * pmt, 2.1))))
        attend_bl = max(35, min(100, round(rng.gauss(78 - 0.10 * pmt, 9), 1)))
        health_bl = int(rng.random() < (0.38 + 0.08 * disability + 0.02 * children_under5))
        households.append(
            {
                "hhid": f"HH{i:05d}",
                "region": region,
                "district": district,
                "village": village,
                "urban": int(region == "Coast" and rng.random() < 0.55),
                "hh_size": hh_size,
                "female_head": female_head,
                "disability_member": disability,
                "children_under5": children_under5,
                "school_age_children": school_age,
                "proxy_means_score": "" if missing_pmt else pmt,
                "eligible_baseline": eligible,
                "food_insecurity_score_bl": food_bl,
                "school_attendance_rate_bl": attend_bl,
                "health_visit_last_month_bl": health_bl,
                "survey_date_bl": survey_date.isoformat(),
                "enum_id_bl": enum,
            }
        )

    # Intentional duplicate records with visible but plausible variation.
    households.extend([dict(households[149]), dict(households[487])])
    households[-2]["enum_id_bl"] = "EN15"
    households[-1]["survey_date_bl"] = "2025-04-18"

    followup = []
    logs = []
    for row in households[:1200]:
        attrit_prob = 0.055 + (0.10 if row["district"] == "Ila" else 0)
        attrited = rng.random() < attrit_prob
        enum = rng.choice(enumerators)
        if row["district"] == "Ila":
            enum = rng.choice(["EN03", "EN04", "EN11"])
        start = date(2026, 3, 1) + timedelta(days=rng.randint(0, 44))
        duration = max(8, rng.gauss(37, 9))
        if enum == "EN03":
            duration = max(4, rng.gauss(17, 5))
        dont_know = max(0, int(rng.gauss(1.2, 1.0) + (3 if enum == "EN11" else 0)))
        module_missing = max(0, int(rng.random() < 0.04) + (1 if enum == "EN11" and rng.random() < 0.12 else 0))
        consent = int(not attrited and rng.random() > 0.01)
        refusal = int(attrited and rng.random() < 0.35)
        logs.append(
            {
                "submission_id": f"SUB{len(logs)+1:05d}",
                "hhid": row["hhid"],
                "round": "followup",
                "enum_id": enum,
                "start_time": f"{start.isoformat()} 09:{rng.randint(0,59):02d}:00",
                "end_time": f"{start.isoformat()} 10:{rng.randint(0,59):02d}:00",
                "duration_minutes": round(duration, 1),
                "consent": consent,
                "refusal": refusal,
                "gps_accuracy": round(max(3, rng.gauss(18, 10)), 1),
                "module_missing_count": module_missing,
                "dont_know_count": dont_know,
            }
        )
        if attrited:
            continue
        base_food = float(row["food_insecurity_score_bl"])
        base_attend = float(row["school_attendance_rate_bl"])
        true_received = int(row["eligible_baseline"]) and rng.random() < 0.86
        self_report = int(true_received or rng.random() < 0.06)
        followup.append(
            {
                "hhid": row["hhid"],
                "survey_date_fu": start.isoformat(),
                "enum_id_fu": enum,
                "food_insecurity_score_fu": max(0, min(12, round(base_food - rng.gauss(0.9 if true_received else 0.25, 1.4)))),
                "school_attendance_rate_fu": max(30, min(100, round(base_attend + rng.gauss(3.5 if true_received else 0.8, 5.5), 1))),
                "health_visit_last_month_fu": int(rng.random() < (0.44 + 0.06 * int(row["disability_member"]))),
                "received_transfer_self_report": self_report,
                "grievance_awareness": int(rng.random() < 0.53),
                "satisfaction_score": max(1, min(5, round(rng.gauss(3.8 if true_received else 2.9, 0.9), 1))),
                "attrition_reason": "",
            }
        )

    payments = []
    for row in households[:1200]:
        provider = rng.choices(providers, weights=[0.45, 0.35, 0.20])[0]
        if row["district"] in ["Ila", "Kalo"]:
            provider = rng.choices(providers, weights=[0.20, 0.55, 0.25])[0]
        enrolled = int(row["eligible_baseline"]) == 1 and rng.random() > (0.075 + (0.06 if row["district"] == "Ila" else 0))
        for cycle in range(1, 5):
            expected = 65 if enrolled else 0
            fail_prob = 0.05 + (0.11 if provider == "MobileCash" and row["district"] == "Ila" else 0)
            failed = int(expected > 0 and rng.random() < fail_prob)
            scheduled = date(2025, 7, 1) + timedelta(days=60 * (cycle - 1))
            delay = max(0, int(rng.gauss(4, 3)))
            if provider == "MobileCash":
                delay += rng.choice([0, 1, 2, 8])
            if row["district"] == "Ila":
                delay += rng.choice([0, 4, 9])
            actual = "" if failed or expected == 0 else (scheduled + timedelta(days=delay)).isoformat()
            paid = 0 if failed else expected
            if expected > 0 and not failed and cycle == 3 and provider == "MobileCash" and rng.random() < 0.11:
                paid = 55
            if expected == 0 and rng.random() < 0.018:
                paid = 65
                actual = (scheduled + timedelta(days=delay)).isoformat()
            payments.append(
                {
                    "hhid": row["hhid"],
                    "payment_cycle": cycle,
                    "scheduled_date": scheduled.isoformat(),
                    "actual_date": actual,
                    "provider": provider,
                    "transfer_amount_expected": expected,
                    "transfer_amount_paid": paid,
                    "failed_payment": failed,
                    "failure_reason": rng.choice(["inactive account", "missing national id", "provider outage"]) if failed else "",
                }
            )

    visits = []
    severe_hh = rng.sample([r["hhid"] for r in households[:1200]], 90)
    for idx, hhid in enumerate(severe_hh, 1):
        hh = next(r for r in households if r["hhid"] == hhid)
        severity = rng.choices(["low", "medium", "high"], weights=[0.45, 0.35, 0.20])[0]
        if idx in [7, 21, 49, 73]:
            severity = "high"
        resolved = int(rng.random() < (0.78 if severity != "high" else 0.48))
        district = hh["district"]
        if idx in [11, 57]:
            district = rng.choice([d for ds in regions.values() for d in ds if d != district])
        visits.append(
            {
                "visit_id": f"VIS{idx:04d}",
                "hhid": hhid,
                "visit_date": (date(2026, 4, 1) + timedelta(days=rng.randint(0, 30))).isoformat(),
                "field_officer_id": rng.choice(field_officers),
                "district": district,
                "issue_category": rng.choice(["payment failed", "registration mismatch", "grievance access", "survey revisit", "beneficiary confusion"]),
                "issue_severity": severity,
                "resolved": resolved,
                "notes": rng.choice([
                    "Household reports account SIM was replaced.",
                    "Village leader requested beneficiary list clarification.",
                    "Respondent asks how to file grievance.",
                    "Payment agent unavailable on scheduled date.",
                    "Back-check could not confirm original respondent.",
                ]),
            }
        )

    backchecks = []
    sampled = rng.sample([r["hhid"] for r in households[:1200]], 180)
    for idx, hhid in enumerate(sampled, 1):
        hh = next(r for r in households if r["hhid"] == hhid)
        mismatch = rng.choices([0, 1, 2, 3], weights=[0.72, 0.18, 0.07, 0.03])[0]
        if hh["district"] == "Ila" and rng.random() < 0.22:
            mismatch += 1
        backchecks.append(
            {
                "backcheck_id": f"BC{idx:04d}",
                "hhid": hhid,
                "backchecker_id": f"BCEN{rng.randint(1,5):02d}",
                "backcheck_date": (date(2026, 4, 5) + timedelta(days=rng.randint(0, 22))).isoformat(),
                "respondent_confirmed": int(rng.random() > 0.04),
                "hh_size_bc": max(1, int(hh["hh_size"]) + rng.choice([-1, 0, 0, 0, 1])),
                "received_transfer_bc": int(rng.random() < 0.76),
                "key_discrepancy_count": mismatch,
                "requires_followup": int(mismatch >= 2),
            }
        )

    codebook = [
        {"variable": "hhid", "label": "Synthetic household identifier", "unit": "household", "notes": "Expected unique within baseline after resolving intentional duplicates"},
        {"variable": "eligible_baseline", "label": "Eligible according to baseline targeting rule", "unit": "household", "notes": "PMT <= 48 or household has member with disability"},
        {"variable": "payment_delay_days", "label": "Days between scheduled and actual payment", "unit": "household-cycle", "notes": "Missing for failed payments and non-beneficiaries"},
        {"variable": "flag_any_quality_issue", "label": "Any data quality issue detected", "unit": "household", "notes": "Constructed from duplicates, range, payment, survey-log, and back-check flags"},
    ]

    write_csv(RAW / "households_baseline.csv", households)
    write_csv(RAW / "households_followup.csv", followup)
    write_csv(RAW / "payments.csv", payments)
    write_csv(RAW / "field_visits.csv", visits)
    write_csv(RAW / "survey_logs.csv", logs)
    write_csv(RAW / "backchecks.csv", backchecks)
    write_csv(RAW / "codebook.csv", codebook)


def build_processed_outputs() -> dict:
    baseline_raw = read_csv(RAW / "households_baseline.csv")
    followup = {r["hhid"]: r for r in read_csv(RAW / "households_followup.csv")}
    payments = read_csv(RAW / "payments.csv")
    logs = read_csv(RAW / "survey_logs.csv")
    backchecks = read_csv(RAW / "backchecks.csv")
    visits = read_csv(RAW / "field_visits.csv")

    seen = set()
    baseline = []
    dup_ids = set()
    for row in baseline_raw:
        if row["hhid"] in seen:
            dup_ids.add(row["hhid"])
            continue
        seen.add(row["hhid"])
        baseline.append(row)

    pay_by_hh = defaultdict(list)
    for p in payments:
        pay_by_hh[p["hhid"]].append(p)

    log_by_hh = {r["hhid"]: r for r in logs if r["round"] == "followup"}
    bc_by_hh = defaultdict(list)
    for b in backchecks:
        bc_by_hh[b["hhid"]].append(b)
    visits_by_hh = defaultdict(list)
    for v in visits:
        visits_by_hh[v["hhid"]].append(v)

    panel = []
    for b in baseline:
        hhid = b["hhid"]
        fu = followup.get(hhid)
        hh_pay = pay_by_hh[hhid]
        eligible = int(b["eligible_baseline"])
        expected_cycles = [p for p in hh_pay if float(p["transfer_amount_expected"]) > 0]
        paid_cycles = [p for p in hh_pay if float(p["transfer_amount_paid"]) > 0]
        delays = [
            (parse_date(p["actual_date"]) - parse_date(p["scheduled_date"])).days
            for p in expected_cycles
            if p["actual_date"]
        ]
        failed = sum(int(p["failed_payment"]) for p in hh_pay)
        underpaid = sum(
            1
            for p in hh_pay
            if float(p["transfer_amount_expected"]) > 0
            and float(p["transfer_amount_paid"]) < float(p["transfer_amount_expected"])
            and int(p["failed_payment"]) == 0
        )
        received_admin = int(any(float(p["transfer_amount_paid"]) > 0 for p in hh_pay))
        self_report = int(fu["received_transfer_self_report"]) if fu else 0
        log = log_by_hh.get(hhid, {})
        bc_flags = sum(int(x["requires_followup"]) for x in bc_by_hh[hhid])
        severe_open = sum(1 for x in visits_by_hh[hhid] if x["issue_severity"] == "high" and int(x["resolved"]) == 0)
        food_fu = float(fu["food_insecurity_score_fu"]) if fu else float("nan")
        attend_fu = float(fu["school_attendance_rate_fu"]) if fu else float("nan")
        duration = float(log["duration_minutes"]) if log else float("nan")
        dont_know = int(log["dont_know_count"]) if log else 0
        module_missing = int(log["module_missing_count"]) if log else 0
        pmt_missing = b["proxy_means_score"] == ""
        flag = int(
            hhid in dup_ids
            or pmt_missing
            or int(b["hh_size"]) <= 0
            or int(b["hh_size"]) > 20
            or (not math.isnan(duration) and duration < 15)
            or dont_know >= 5
            or module_missing >= 2
            or self_report != received_admin
            or bc_flags > 0
            or severe_open > 0
        )
        panel.append(
            {
                "hhid": hhid,
                "region": b["region"],
                "district": b["district"],
                "village": b["village"],
                "eligible_baseline": eligible,
                "female_head": b["female_head"],
                "disability_member": b["disability_member"],
                "hh_size": b["hh_size"],
                "proxy_means_score": b["proxy_means_score"],
                "followup_observed": int(fu is not None),
                "received_admin": received_admin,
                "received_transfer_self_report": self_report,
                "coverage_eligible": int(eligible == 1 and received_admin == 1),
                "leakage_ineligible": int(eligible == 0 and received_admin == 1),
                "exclusion_eligible": int(eligible == 1 and received_admin == 0),
                "payment_delay_mean": round(mean(delays), 2) if delays else "",
                "failed_payment_count": failed,
                "underpaid_cycle_count": underpaid,
                "food_insecurity_score_bl": b["food_insecurity_score_bl"],
                "food_insecurity_score_fu": "" if math.isnan(food_fu) else food_fu,
                "food_insecurity_change": "" if math.isnan(food_fu) else round(food_fu - float(b["food_insecurity_score_bl"]), 2),
                "school_attendance_rate_bl": b["school_attendance_rate_bl"],
                "school_attendance_rate_fu": "" if math.isnan(attend_fu) else attend_fu,
                "school_attendance_change": "" if math.isnan(attend_fu) else round(attend_fu - float(b["school_attendance_rate_bl"]), 2),
                "duration_minutes_fu": "" if math.isnan(duration) else duration,
                "dont_know_count_fu": dont_know,
                "module_missing_count_fu": module_missing,
                "backcheck_followup_required": bc_flags,
                "open_high_severity_visit": severe_open,
                "flag_any_quality_issue": flag,
            }
        )

    write_csv(PROCESSED / "analysis_household_panel.csv", panel)

    # Household-level flags for field follow-up.
    followup_list = [
        {
            "hhid": r["hhid"],
            "district": r["district"],
            "priority": "high"
            if int(r["open_high_severity_visit"]) or int(r["backcheck_followup_required"]) or int(r["failed_payment_count"]) >= 2
            else "medium",
            "reason": "; ".join(
                reason
                for reason, yes in [
                    ("admin/self-report mismatch", int(r["received_admin"]) != int(r["received_transfer_self_report"])),
                    ("short survey duration", r["duration_minutes_fu"] != "" and float(r["duration_minutes_fu"]) < 15),
                    ("back-check follow-up", int(r["backcheck_followup_required"]) > 0),
                    ("open high-severity visit", int(r["open_high_severity_visit"]) > 0),
                    ("repeated failed payment", int(r["failed_payment_count"]) >= 2),
                ]
                if yes
            ),
        }
        for r in panel
        if int(r["flag_any_quality_issue"])
    ]
    write_csv(PROCESSED / "data_quality_flags.csv", followup_list)
    write_csv(TABLES / "field_followup_list.csv", followup_list[:120])

    # Tables.
    eligible = [r for r in panel if int(r["eligible_baseline"]) == 1]
    ineligible = [r for r in panel if int(r["eligible_baseline"]) == 0]
    observed = [r for r in panel if int(r["followup_observed"]) == 1]
    targeting = [
        {"indicator": "Baseline households", "value": len(panel), "unit": "households"},
        {"indicator": "Eligible at baseline", "value": len(eligible), "unit": "households"},
        {"indicator": "Coverage among eligible", "value": fmt(pct(sum(int(r["coverage_eligible"]) for r in eligible), len(eligible))), "unit": "percent"},
        {"indicator": "Exclusion among eligible", "value": fmt(pct(sum(int(r["exclusion_eligible"]) for r in eligible), len(eligible))), "unit": "percent"},
        {"indicator": "Leakage to ineligible", "value": fmt(pct(sum(int(r["leakage_ineligible"]) for r in ineligible), len(ineligible))), "unit": "percent"},
        {"indicator": "Follow-up response rate", "value": fmt(pct(len(observed), len(panel))), "unit": "percent"},
    ]
    write_csv(TABLES / "targeting_summary.csv", targeting)

    by_provider = defaultdict(list)
    for p in payments:
        by_provider[p["provider"]].append(p)
    provider_rows = []
    for provider, rows in sorted(by_provider.items()):
        expected = [r for r in rows if float(r["transfer_amount_expected"]) > 0]
        paid = [r for r in expected if float(r["transfer_amount_paid"]) > 0]
        delays = [
            (parse_date(r["actual_date"]) - parse_date(r["scheduled_date"])).days
            for r in paid
            if r["actual_date"]
        ]
        provider_rows.append(
            {
                "provider": provider,
                "eligible_cycles": len(expected),
                "failed_payment_rate": fmt(pct(sum(int(r["failed_payment"]) for r in expected), len(expected))),
                "underpayment_rate": fmt(pct(sum(float(r["transfer_amount_paid"]) < float(r["transfer_amount_expected"]) and int(r["failed_payment"]) == 0 for r in expected), len(expected))),
                "mean_delay_days": fmt(mean(delays)),
            }
        )
    write_csv(TABLES / "payment_reliability_summary.csv", provider_rows)
    write_csv(PROCESSED / "payment_reliability_summary.csv", provider_rows)

    welfare = [
        {
            "indicator": "Food insecurity score",
            "baseline": fmt(mean([float(r["food_insecurity_score_bl"]) for r in observed])),
            "followup": fmt(mean([float(r["food_insecurity_score_fu"]) for r in observed])),
            "change": fmt(mean([float(r["food_insecurity_change"]) for r in observed])),
            "interpretation": "Lower is better",
        },
        {
            "indicator": "School attendance rate",
            "baseline": fmt(mean([float(r["school_attendance_rate_bl"]) for r in observed])),
            "followup": fmt(mean([float(r["school_attendance_rate_fu"]) for r in observed])),
            "change": fmt(mean([float(r["school_attendance_change"]) for r in observed])),
            "interpretation": "Higher is better",
        },
    ]
    write_csv(TABLES / "welfare_change_summary.csv", welfare)

    enum_stats = defaultdict(lambda: {"n": 0, "short": 0, "dk": 0, "missing": 0})
    for r in logs:
        e = r["enum_id"]
        enum_stats[e]["n"] += 1
        enum_stats[e]["short"] += float(r["duration_minutes"]) < 15
        enum_stats[e]["dk"] += int(r["dont_know_count"]) >= 5
        enum_stats[e]["missing"] += int(r["module_missing_count"]) >= 2
    enum_rows = [
        {
            "enum_id": e,
            "submissions": s["n"],
            "short_duration_rate": fmt(pct(s["short"], s["n"])),
            "high_dont_know_rate": fmt(pct(s["dk"], s["n"])),
            "module_missing_rate": fmt(pct(s["missing"], s["n"])),
        }
        for e, s in sorted(enum_stats.items())
    ]
    write_csv(TABLES / "enumerator_quality_summary.csv", enum_rows)

    with (TABLES / "targeting_summary.md").open("w", encoding="utf-8") as f:
        f.write("| Indicator | Value | Unit |\n|---|---:|---|\n")
        for r in targeting:
            f.write(f"| {r['indicator']} | {r['value']} | {r['unit']} |\n")

    insights = {
        "project": "Lumora Family Support Grant Evaluation",
        "round": "Follow-up",
        "headline": "Follow-up data show broad eligible coverage, but payment reliability and field data quality are uneven.",
        "coverage_eligible_pct": targeting[2]["value"],
        "exclusion_eligible_pct": targeting[3]["value"],
        "leakage_ineligible_pct": targeting[4]["value"],
        "followup_response_pct": targeting[5]["value"],
        "highest_delay_provider": max(provider_rows, key=lambda r: float(r["mean_delay_days"]))["provider"],
        "field_followup_households": len(followup_list),
        "caution": "Before/after welfare changes are descriptive and should not be presented as causal program impacts.",
    }
    return {"panel": panel, "targeting": targeting, "provider_rows": provider_rows, "welfare": welfare, "enum_rows": enum_rows, "insights": insights}


def write_qa(outputs: dict) -> None:
    raw_files = sorted(p.name for p in RAW.glob("*.csv"))
    rows = [
        "# Synthetic Data Design",
        "",
        f"Seed: `{SEED}`",
        "",
        "Raw files:",
        *[f"- `{name}`" for name in raw_files],
        "",
        "Intentional issues:",
        "- duplicate baseline household IDs;",
        "- implausible household sizes;",
        "- PMT missingness concentrated under one enumerator;",
        "- follow-up attrition concentrated in Ila district;",
        "- short survey duration and high don't-know counts for selected enumerators;",
        "- payment delays concentrated by provider/district;",
        "- back-check and field-visit discrepancies requiring follow-up.",
        "",
        "Important caution: these data are synthetic and should only be used for training.",
    ]
    (QA / "synthetic_data_design.md").write_text("\n".join(rows) + "\n", encoding="utf-8")

    hfc = [
        "# High-Frequency Check Summary",
        "",
        f"- Households flagged for field follow-up: {outputs['insights']['field_followup_households']}",
        f"- Follow-up response rate: {outputs['insights']['followup_response_pct']} percent",
        f"- Provider with highest mean delay: {outputs['insights']['highest_delay_provider']}",
        "- Priority: review short-duration surveys, resolve open severe field visits, and reconcile payment mismatches before the next cycle.",
        "",
        "Language note: flags indicate cases for review. They are not evidence of misconduct by enumerators, providers, or households.",
    ]
    (QA / "hfc_summary.md").write_text("\n".join(hfc) + "\n", encoding="utf-8")


def main() -> None:
    ensure_dirs()
    generate_raw_data()
    outputs = build_processed_outputs()
    write_qa(outputs)
    print("Materialized Lumora demo data, tables, and QA reports.")
    print(f"Raw files: {len(list(RAW.glob('*.csv')))}")
    print(f"Processed rows: {len(outputs['panel'])}")
    print("Figures are intentionally generated by Stata, not Python.")


if __name__ == "__main__":
    main()
